import type { MetadataRoute } from "next";

const SITE_URL = "https://pickleball-card-games.vercel.app";

// Backlog F483 - robots.txt generated by Next.
export default function robots(): MetadataRoute.Robots {
  return {
    rules: { userAgent: "*", allow: "/", disallow: "/api/" },
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
